// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://celqsrqgrgabkxxsipbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbHFzcnFncmdhYmt4eHNpcGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQ2MTcsImV4cCI6MjA2NTUxMDYxN30.H5RIjtwb0QiqwLwaHQZnNqHlchcFxOShkvEXPJSWE2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);